name: example
description: Navbar Router Example
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  navbar_router:
    path: ../
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  badges:

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
